  - ec2:
      keypair: vindinium-ai-challenge-server
      aws_access_key: "{{ ec2_access_key  }}"
      aws_secret_key: "{{ ec2_secret_key  }}"
      instance_type: t2.micro
      image: ami-f9dd458a
      group: vindinium 
      region: eu-west-1
      wait: yes
      count: "{{ count }}" 
      instance_tags: 
        Name: "{{ name }}" 
